### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by bradymholt** [bradymholt/xertz#1]
- [ ] rss feed only contains excerpt; consider using full 
- [ ] Implement watch with incremental build
- [ ] Optimize
  - [ ] Hash processed files
  - [ ] Do not load files twice
- [ ] Fix style of AMP in scaffold
- [ ] .hbs templates
  - [ ] foo.hbs > foo.html
  - [ ] Layount in frontmatter
